include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  plugins:
    - custom_lint

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - require_trailing_commas
    - unawaited_futures
    - prefer_single_quotes
    - sort_child_properties_last
    - use_build_context_synchronously
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
